### ISSUE TITLE
Automatic logout after 20 mins

### ISSUE THREAD

**Issue by rgedwill** [omou-org/mainframe#143]
Automatically log user session out after 20 minutes.

Look into saving user session data - i.e if a user is halfway through filling out a form, can the form data be prepopulated when they log back in?

I've seen a popular third party library https://django-session-security.readthedocs.io/en/latest/,  but I'm not sure if it's necessary. 

I think what will be involved is a timer on the front-end that, after 20 minutes, sends a request to the backend to trigger a logout. 

There's an interesting decorator i'd never heard of mentioned that may be useful https://stackoverflow.com/a/25264881/5877575

**Comment by dhuangg** [comment]
read the product description i wrote for this feature. django graphene jwt
allows you to configure session timeout rules. look at the references i
linked in the document

**Comment by rgedwill** [comment]
This was for user story AN
