### ISSUE TITLE
Course Availabilities update mutation not updating sessions properly

### ISSUE THREAD

**Issue by dhuangg** [omou-org/mainframe#184]
# Steps to Recreate
1. Create a course with multiple availabilities (e.g. Monday 3:00pm - 4:00pm, Wednesday 3:00pm - 4:00pm)
2. Update the course availabilities to move from 1 day to another (e.g. Monday 3:00pm - 4:00pm, -Wednesday 3:00pm - 4:00pm- **Friday 3:00pm - 4:00pm**)
3. The Wednesday session will still remain and have a status of "active"

The example below shows how SAT Math 2's time was changed + the day of the week was changed to result in several duplicates of a session on the same day (2021-01-28T23:00)
<img width="531" alt="Screen Shot 2021-01-29 at 12 50 04 PM" src="https://user-images.githubusercontent.com/12959959/106325954-8983ca80-6230-11eb-8038-a683535c8632.png">

![Screen Shot 2021-01-29 at 12 49 54 PM](https://user-images.githubusercontent.com/12959959/106325949-87ba0700-6230-11eb-9204-49f732d22ee2.png)

![Screen Shot 2021-01-29 at 1 42 59 PM](https://user-images.githubusercontent.com/12959959/106330621-66f5af80-6238-11eb-8725-36bd2b186d1e.png)

# Development Todo's 
TBD - need to discuss with @katiebelleho to figure out how to handle this first.

**Comment by dhuangg** [comment]
Discussed with @katiebelleho about this. Instead of deactiving sessions, we will be shifting them to the nearest upcoming course availability (slot) set by the user. 

This logic would only for sessions in the future (sessions that haven't happened yet include the ones upcoming on the current day). 

Here's an illustration of this idea:
![MicrosoftTeams-image (17)](https://user-images.githubusercontent.com/12959959/106336247-5c8ce300-6243-11eb-982e-b4c15e3f7189.png)

# Development Todo's
- [ ] Change session updating logic to reflect idea above
- [ ] Refactor "courseAvailability" to "sessionSlot"

**Comment by tigermli** [comment]
I tried the scenario above out on my backend and am not getting duplicate sessions. Here were my steps:

1) Create New Course with following scheduling (today is 2021-1-29)
create mutation:
<img width="252" alt="Screen Shot 2021-01-29 at 3 44 58 PM" src="https://user-images.githubusercontent.com/11560193/106338941-f061ad80-6249-11eb-99f4-f341198f2810.png">

result:
<img width="232" alt="Screen Shot 2021-01-29 at 3 44 48 PM" src="https://user-images.githubusercontent.com/11560193/106338945-f3f53480-6249-11eb-8c5d-3c56e27a129c.png">

2) Add an additional Friday session
update mutation:
<img width="250" alt="Screen Shot 2021-01-29 at 3 50 29 PM" src="https://user-images.githubusercontent.com/11560193/106339001-24d56980-624a-11eb-8534-2afa9403b55e.png">

result:
<img width="229" alt="Screen Shot 2021-01-29 at 3 50 10 PM" src="https://user-images.githubusercontent.com/11560193/106339009-2868f080-624a-11eb-80e4-d7c170a998a1.png">

**Comment by dhuangg** [comment]
@tigermli You're right - the availability list doesn't create any duplicates, but I think it's duplicating past sessions. 
![Screen Shot 2021-01-29 at 5 23 00 PM](https://user-images.githubusercontent.com/12959959/106342680-be0a7d00-6256-11eb-893a-e187a7325a10.png)

Once we're looking at the new sessions, we're good to go. 
![Screen Shot 2021-01-29 at 5 23 16 PM](https://user-images.githubusercontent.com/12959959/106342689-c5318b00-6256-11eb-97cc-1d7e03936f43.png)

Visual representation of what I'm seeing: 
<img width="1207" alt="Screen Shot 2021-01-29 at 5 25 37 PM" src="https://user-images.githubusercontent.com/12959959/106342765-0c1f8080-6257-11eb-8d16-26ffad5b8c45.png">

Also, can you confirm that the code is doing the logic outlined in the comment above?

**Comment by dhuangg** [comment]
can't replicate this bug, but discovered new bug - sessions created on course creation are off by 1 day. 

To resolve current issue - will provide options for when the user wants to change a course availability:
1. Delete all future session notes
2. Keep all future session notes as course notes
3. Cancel

**Comment by dhuangg** [comment]
closing this issue for now until we can replicate the old session duplication bug
