### ISSUE TITLE
Filter by availability breaking

### ISSUE THREAD

**Issue by dhuangg** [omou-org/mainframe#33]
For the course search endpoint `/search/course/` when I have the "availability" filter as "open" or "filled" I'm getting an error. Screenshot of error below: 

![Screen Shot 2020-01-04 at 8 31 33 AM](https://user-images.githubusercontent.com/12959959/71768630-a1bdd480-2ecc-11ea-9b50-2516ef2ac1fb.png)

**Comment by tigermli** [comment]
Fixed in latest push. All filtering by deprecated course_id attribute not down by course's id attribute
