### ISSUE TITLE
Search by sessions

### ISSUE THREAD

**Issue by dhuangg** [omou-org/mainframe#34]
## Background
Since we originally only planned on releasing with search by course and search by accounts, we didn't address this use case. Right now, @gglinoga is building out the dashboard feature which requires a list of upcoming sessions (screenshot below). This isn't prioritized for the demo on Monday (1/6), so take your time if you need it. 

![Screen Shot 2020-01-04 at 8 35 22 AM](https://user-images.githubusercontent.com/12959959/71768678-332d4680-2ecd-11ea-8820-fb0448294597.png)

### Querying
Have the endpoint be similar to the other 2: `/search/session/` 
We want to search by text in the following session fields: 

- Session start date
- Session start time
- Session's course instructor
- Session's course enrollments
- Session's course title 

The first 2 should be easy since they're associated with the session object itself (screenshot below). But the latter two will be more difficult since you'd need to query the associated course with the session. Prioritize the first 2, and we can discuss an approach for querying through the latter 3 fields after the demo. 
![Screen Shot 2020-01-04 at 8 39 21 AM](https://user-images.githubusercontent.com/12959959/71768725-d716f200-2ecd-11ea-9090-1e4270f902af.png)

### Sorting/Filtering
There may be more sorting/filtering that comes up for this endpoint, but this ticket will only address the main current use case: getting upcoming sessions. 

Create the following parameters:
- query
- timeFilter
  - all
  - past
  - future
- sort
  - timeAsc
  - timeDsc 

### query
This is an optional parameter. If there's something in this param then search by the query. If there's nothing in the param then return all sessions matching the other filters. 

#### timeFilter
This filter has to be on for the endpoint to work. 
**all** gives sessions from both the past and the future based on the current requested time
**past** gives sessions only from the past based on the current requested time
**future** gives sessions only from the future based on the current requested time

#### Sort
These sorts will only work if we have the "past" or "future" filters on. 
**timeAsc** : endpoint will be give sessions that are furthest away into the future/past from the time of the request 

Example: I call `/search/session/?timeFilter=past&sort=timeAsc` at 1/4/2020 at 3pm, and there are 3 sessions ( 1/3/2020 @5pm, 1/3/2020 @6pm, 1/1/2020 @9pm). I'm expecting the 3 sessions in the following order: 1/1/2020 @9pm, 1/3/2020 @6pm, 1/3/2020 @5pm).

**timeDsc**: endpoint will give sessions that are closest into the future/past from the time of the request.

Example: I call `/search/session/?timeFilter=future&sort=timeDsc` at 1/4/2020 at 3pm, and there are 3 sessions ( 1/4/2020 @5pm, 1/4/2020 @6pm, 1/6/2020 @9pm). I'm expecting the 3 sessions in the following order: 1/4/2020 @5pm, 1/4/2020 @6pm, 1/6/2020 @9pm).

**Comment by tigermli** [comment]
Update: Adding "today" option to the timeFilter for the sessions search that filters only for sessions today.

**Comment by tigermli** [comment]
Code pushed and in pull request review

**Comment by tigermli** [comment]
@gglinoga 
Session Filters

"query": some search query string

"time":
- "today": all sessions from today
- "past": all sessions before today
- "future": all sessions after today

"sort":
- "timeAsc": earliest to latest
- "timeDesc": latest to earliest

ex)
"/search/session/?time=today&sort=timeAsc"
list all sessions today in ascending order
