### ISSUE TITLE
Registration Objects Not Returning

### ISSUE THREAD

**Issue by dhuangg** [omou-org/mainframe#37]
## Background
When I request a payment object, I'm expecting a list of Registration objects. 

## Problem
I'm not seeing the registration objects :( 
<img width="448" alt="Screen Shot 2020-01-04 at 9 14 48 AM" src="https://user-images.githubusercontent.com/12959959/71769192-af765880-2ed2-11ea-9919-6bf27f6f67af.png">

**Comment by jerrylinew** [comment]
This now returns with all the registration and enrollment details. 
<img width="522" alt="Screen Shot 2020-01-04 at 4 36 19 PM" src="https://user-images.githubusercontent.com/9204182/71773355-76f56f80-2f10-11ea-97ca-9c0b2f3ac7c6.png">
