### ISSUE TITLE
Course Catalog down on prod

### ISSUE THREAD

**Issue by dhuangg** [omou-org/mainframe#41]
This is a high priority ticket. 

We're getting a 500 on prod for `/course/catalog/` Screenshots for reference
![Screen Shot 2020-01-04 at 1 56 39 PM](https://user-images.githubusercontent.com/12959959/71772116-676b2c00-2efa-11ea-85f9-545b9e81467b.png)
![Screen Shot 2020-01-04 at 1 56 44 PM](https://user-images.githubusercontent.com/12959959/71772117-6d610d00-2efa-11ea-9f48-d1f76c585299.png)

**Comment by jerrylinew** [comment]
did open heart surgery on prod to fix this
