### ISSUE TITLE
Applying parent account balance to price quote + payment

### ISSUE THREAD

**Issue by dhuangg** [omou-org/mainframe#48]
## Background
Currently there are 2 planned ways for an account balance to be credited
1. When a student unenrolls in a course, the parent's account balance will be credited with the total tuition from all the registrations. #47 
2. When a session gets extended, the sessions need to be pro-rated again and credited to their account balance. #35 

When there's credit in the account balance, it should be calculated in the price quote. 

## Development
- [x] include an additional "apply_account_balance" boolean field in the POST request body
- [x] include an additional "parent_id" integer id field in the POST request body (only used when apply_account_balance = True)
- [x] if "apply_account_balance" is true, then return the price quote that looks like:
```
{   
   sub_total: //total of all the course tuitions,
   account_balance: //total account balance
   discounts: [ //array of discounts ],
   price_adjustment: 100,
   total: // total = sub_total - account_balance - discounts
}
```

**Comment by tigermli** [comment]
As discussed with @dhuangg , parent_id is included in conjunction with apply_account_balance in POST request body
