### ISSUE TITLE
POST Instructor Availability Not Working

### ISSUE THREAD

**Issue by dhuangg** [omou-org/mainframe#57]
When we post an instructor availability, the response we get is "null" for all the times
<img width="941" alt="Screen Shot 2020-01-16 at 10 55 39 PM" src="https://user-images.githubusercontent.com/12959959/72590756-5daad680-38b3-11ea-8fc7-cf960847d88e.png">

**Comment by dhuangg** [comment]
@NeilAllavarpu confirmation that i'm getting this bug too

**Comment by dhuangg** [comment]
Updated screenshot
![Screen Shot 2020-01-19 at 12 18 58 AM](https://user-images.githubusercontent.com/12959959/72677438-51f51680-3a51-11ea-8b9a-6e976f1c310f.png)

**Comment by tigermli** [comment]
Pushed to master. Should give error when trying to post availability with same instructor id as existing availability.

Let me know if updating works

**Comment by tigermli** [comment]
Need to directly specify attribute values in request body now
