### ISSUE TITLE
Filter sessions by course ID

### ISSUE THREAD

**Issue by dhuangg** [omou-org/mainframe#59]
## Background
Scheduler endpoint's primary use case has been to display sessions on the scheduler view. However, we need to be able to display sessions for the course session status view for an enrollment (screenshot below).
![Screen Shot 2020-01-18 at 7 11 21 PM](https://user-images.githubusercontent.com/12959959/72684995-60b3eb80-3a9a-11ea-873b-790eed67b4a8.png)

## Development
- [x] Add a param to the GET scheduler/sessions/ endpoint to fetch all the sessions in a course

**Comment by tigermli** [comment]
Pushed to master.
Session endpoint now filters by course_id in url
