### ISSUE TITLE
Update Search Courses to include count and page 

### ISSUE THREAD

**Issue by CalvinFronda** [omou-org/mainframe#71]
Thanks for setting up the page and count for accounts, they are helping a lot with the front-end development. 

This fix should be relatively easy because you just need to copy what you did with the "search/accounts/" and move add it to "search/course". 

Response from accounts ("search/account").
The red square is the correct response.
<img width="586" alt="Screen Shot 2020-02-12 at 12 13 51 AM" src="https://user-images.githubusercontent.com/40410706/74317008-76ca6a00-4d2f-11ea-992b-b4c04a325550.png">

Response from courses ("search/course").
This is where we would need to add the models for count and page.
<img width="635" alt="Screen Shot 2020-02-12 at 12 31 09 AM" src="https://user-images.githubusercontent.com/40410706/74317103-a0839100-4d2f-11ea-88ff-1730589e619b.png">

**Comment by dhuangg** [comment]
This ticket should be closed. it's not an issue on the frontend @CalvinFronda check the request to see 
![Screen Shot 2020-02-12 at 9 10 47 PM](https://user-images.githubusercontent.com/12959959/74407397-c6b83800-4de6-11ea-99c9-bb788593c4b3.png)
